server:
  port: 4040
  forward-headers-strategy: native
  ssl:
    enabled: false
    key-store: file:/Users/kuredogyon/Documents/unitybackend/keystore.p12
    key-store-password: root1234  # 키스토어 비밀번호 입력
    key-store-type: PKCS12
    key-alias: myssl  # 위에서 설정한 alias 이름

  servlet:
    session:
      cookie:
        same-site: none

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
            redirect-uri: http://localhost:4040/login/oauth2/code/google
            authorizationGrantType: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
